# FatDockerfile
FROM python:3.11-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
       gcc \
       build-essential \
       python3-dev \
       pkg-config \
       dos2unix \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
CMD ["bash"]